Laboratory work #7, Darya Krinochkina - 20FPL1
fipl-hse/2023-hello-llm pull request #14
Opened 2024-01-12 12:51 UTC by DashaKrinochkina

2024-01-18 15:39 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +# for pull-request
Remove

2024-01-18 15:39 UTC, SalnikovIgor commented
Necessary implementation of loading your dataset.

2024-01-22 17:59 UTC, SalnikovIgor commented
It's time to write the loading of your dataset.

2024-01-26 18:30 UTC, SalnikovIgor commented
Fix tests

2024-01-29 20:52 UTC, SalnikovIgor requested changes
Fix comments and implement model analysis

2024-01-29 20:52 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +        """
New line

2024-01-29 20:52 UTC, SalnikovIgor commented on lab_7_llm/settings.json
> +}
New line

2024-02-05 18:46 UTC, SalnikovIgor requested changes
Fix past comments

2024-02-10 17:58 UTC, SalnikovIgor requested changes
Fix comments and implemetnt dataset inference

2024-02-10 17:58 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +        print(tokens.keys())
Delete

2024-02-11 21:34 UTC, SalnikovIgor requested changes

2024-02-11 21:34 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +        tokenizer = AutoTokenizer.from_pretrained(self._model_name)
Init `tokenizer` as class parameter

2024-02-12 10:16 UTC, DashaKrinochkina commented on lab_7_llm/main.py
> +        tokenizer = AutoTokenizer.from_pretrained(self._model_name)
done

2024-02-13 16:36 UTC, closed without merging