Laboratory work #7, Irina Kurnakova - 20FPL1
fipl-hse/2023-hello-llm pull request #26
Opened 2024-01-15 18:16 UTC by IrinaKurnakova

2024-01-18 15:40 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +
Delete

2024-01-18 15:40 UTC, SalnikovIgor commented
Necessary implementation of loading your dataset.

2024-01-22 18:00 UTC, SalnikovIgor commented
It's time to write the loading of your dataset.

2024-01-26 16:37 UTC, SalnikovIgor commented
And again: it's time to write the loading of your dataset.

2024-01-29 20:56 UTC, SalnikovIgor requested changes
Fix comments and implement model analysis

2024-01-29 20:56 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +        self._raw_data = dataset_df
Two operations can be reduced into one

2024-02-05 11:16 UTC, IrinaKurnakova commented
I don't know what's wrong with tests(

2024-02-05 19:30 UTC, SalnikovIgor requested changes

2024-02-05 19:30 UTC, SalnikovIgor commented on lab_7_llm/start.py
> +    sample = dataset.__getitem__(0)
You shouldn't take one element using a dunder methods. If you can't use` next ... iter` use `for ... in ...` once

2024-02-10 18:11 UTC, SalnikovIgor requested changes
When do you plan to implement a service for a score of 10?

2024-02-10 19:28 UTC, SalnikovIgor requested changes
It's time to move on to task number 10

2024-02-13 16:41 UTC, closed without merging