Laboratory work #7, Pareshina Evgenia - 20FPL2
fipl-hse/2023-hello-llm pull request #29
Opened 2024-01-16 10:34 UTC by eapareshina

2024-01-18 16:46 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +
Delete line

2024-01-18 16:46 UTC, SalnikovIgor commented
Necessary implementation of loading your dataset.

2024-01-22 18:16 UTC, SalnikovIgor commented
It's time to write the loading of your dataset.

2024-01-26 16:35 UTC, SalnikovIgor commented
And again: it's time to write the loading of your dataset.

2024-01-29 21:28 UTC, SalnikovIgor commented
And again: it's time to write the loading of your dataset.

2024-02-05 22:40 UTC, SalnikovIgor commented
It's time to start doing your first lab.

2024-02-10 19:28 UTC, SalnikovIgor commented
It's time to start doing your first lab.

2024-02-29 23:32 UTC, SalnikovIgor requested changes
It's time to start doing your first lab.

2024-03-05 18:58 UTC, SalnikovIgor requested changes
It's time to start doing your first lab.

2024-03-09 20:37 UTC, SalnikovIgor requested changes
It's time to start doing your first lab.

2024-03-10 13:56 UTC, eapareshina commented on lab_7_llm/main.py
> +
Done

2024-03-10 18:39 UTC, eapareshina reviewed
comments were taken into account

2024-03-10 18:55 UTC, SalnikovIgor requested changes

2024-03-10 18:55 UTC, SalnikovIgor commented on lab_7_llm/main.py
> +# from torch.utils.data.dataloader import DataLoader
Delete or unskip

2024-03-10 18:55 UTC, SalnikovIgor commented on requirements.txt
> +datasets==2.16.1
Add line `--extra-index-url https://download.pytorch.org/whl/cpu`

2024-03-10 18:57 UTC, SalnikovIgor commented
Fix minor comments and start lab 8

2024-03-10 19:11 UTC, eapareshina commented
> Fix minor comments and start lab 8

Thank you very much! Comments are already fixed

2024-03-12 15:37 UTC, closed without merging