Laboratory work #8, Irina Kurnakova - 20FPL1
fipl-hse/2023-hello-llm pull request #47
Opened 2024-02-20 08:41 UTC by IrinaKurnakova

2024-02-25 14:48 UTC, SalnikovIgor requested changes

2024-02-25 14:48 UTC, SalnikovIgor commented on lab_7_llm/main.py
>  Neural machine translation module.
Laboratory work № 8 must be completed in the corresponding files.

2024-02-25 14:48 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +
Great changes 👍

2024-02-29 23:30 UTC, SalnikovIgor requested changes
Fix past comments

2024-03-05 18:56 UTC, SalnikovIgor requested changes

2024-03-05 18:56 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +    _raw_data: DataFrame
Are you sure this announcement is necessary?

2024-03-05 18:56 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +    def raw_data(self) -> DataFrame:
And this?

2024-03-05 18:56 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +        tokenizer = AutoTokenizer.from_pretrained(self._model_name)
Initialize as a class parameter

2024-03-05 18:56 UTC, SalnikovIgor commented on requirements.txt
> +datasets==2.16.1
Add line `--extra-index-url https://download.pytorch.org/whl/cpu`

2024-03-06 09:55 UTC, IrinaKurnakova commented on requirements.txt
> +datasets==2.16.1
Done

2024-03-06 10:51 UTC, IrinaKurnakova commented on lab_8_llm/main.py
> +    _raw_data: DataFrame
Yes, because otherwise this error appears: 
Argument 1 to "RawDataPreprocessor" has incompatible type "DataFrame | None"; expected "DataFrame"  [arg-type]

2024-03-06 10:57 UTC, IrinaKurnakova commented on lab_8_llm/main.py
> +    def raw_data(self) -> DataFrame:
the same situation

2024-03-09 20:32 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +    _raw_data: DataFrame
Need to add a check: `_raw_data` containt `None`? If yes, then rise error

2024-03-09 20:35 UTC, SalnikovIgor requested changes

2024-03-09 20:35 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +    def raw_data(self) -> DataFrame:
Comment above

2024-03-12 15:41 UTC, closed without merging