Laboratory work #8, Darya Bugakova - 20FPL1
fipl-hse/2023-hello-llm pull request #50
Opened 2024-02-21 17:04 UTC by daribbb

2024-02-25 15:11 UTC, SalnikovIgor requested changes

2024-02-25 15:11 UTC, SalnikovIgor commented on requirements.txt
> +datasets==2.16.1
Add line  `--extra-index-url https://download.pytorch.org/whl/cpu`  if `torch` is needed

2024-02-29 23:29 UTC, SalnikovIgor requested changes
Fix past comments

2024-03-05 18:50 UTC, SalnikovIgor requested changes
Fix past comments

2024-03-09 20:25 UTC, SalnikovIgor requested changes

2024-03-09 20:25 UTC, SalnikovIgor commented on lab_7_llm/main.py
>  from pathlib import Path
Checkout the files from 7 lab to the master

2024-03-10 18:25 UTC, SalnikovIgor requested changes

2024-03-10 18:25 UTC, SalnikovIgor commented on lab_8_llm/main.py
> +    A class that imports the HuggingFace dataset..
..?

2024-03-10 19:49 UTC, daribbb commented on lab_8_llm/main.py
> +    A class that imports the HuggingFace dataset..
fixed this

2024-03-12 15:42 UTC, closed without merging