Laboratory work #8, Eliseykina Ekaterina- 20FPL1
fipl-hse/2023-hello-llm pull request #72
Opened 2024-03-09 19:00 UTC by reginafeles

2024-03-09 20:08 UTC, reginafeles commented
I'm a little doubtful

The model is trained on three classes, and the dataset is binary
I had to spend more time on the evaluator and “guessing” how exactly standardize the targets so that everything would match the references

2024-03-10 18:04 UTC, SalnikovIgor requested changes

2024-03-10 18:04 UTC, SalnikovIgor commented on seminars/seminar_01_16_2024/assets/danetqa_example.csv
>  Был ли кетчуп в читосе?,Текущий каталог продукции размещен на сайте производителя. Кетчуп  Колбаска и бекон  Краб  Луковые кольца  Паприка  Пицца  Рождественская индейка  Сметана и лук  Стейк на пыла
Delete from PR

2024-03-10 21:17 UTC, reginafeles commented on seminars/seminar_01_16_2024/assets/danetqa_example.csv
>  Был ли кетчуп в читосе?,Текущий каталог продукции размещен на сайте производителя. Кетчуп  Колбаска и бекон  Краб  Луковые кольца  Паприка  Пицца  Рождественская индейка  Сметана и лук  Стейк на пыла
Done

2024-03-12 15:52 UTC, closed without merging