Laboratory work #8, Pareshina Evgenia - 20FPL2
fipl-hse/2023-hello-llm pull request #75
Opened 2024-03-10 21:15 UTC by eapareshina

2024-03-16 20:49 UTC, SalnikovIgor requested changes

2024-03-16 20:49 UTC, SalnikovIgor commented on lab_7_llm/main.py
>  Neural machine translation module.
Checkout files of lab 7 to master

2024-03-16 20:49 UTC, SalnikovIgor commented on requirements.txt
> +transformers==4.37.2
New line

2024-03-18 07:19 UTC, eapareshina commented on requirements.txt
> +transformers==4.37.2
done

2024-03-18 07:20 UTC, eapareshina commented on lab_7_llm/main.py
>  Neural machine translation module.
done

2024-03-18 21:52 UTC, closed without merging