Laboratory work #8, Smirnova Anastasia - 20FPL1
fipl-hse/2023-hello-llm pull request #77
Opened 2024-03-16 12:46 UTC by Smirnova23

2024-03-16 20:51 UTC, SalnikovIgor requested changes
Fix comments and tests

2024-03-16 20:51 UTC, SalnikovIgor commented on lab_7_llm/main.py
Checkout the files from 7 lab to the master

2024-03-16 20:51 UTC, SalnikovIgor commented on requirements.txt
> +transformers==4.38.2
New line

2024-03-17 09:02 UTC, Smirnova23 commented on requirements.txt
> +transformers==4.38.2
fixed comments and tests

2024-03-18 21:53 UTC, closed without merging